

class MessageType {

  /*
  action: 0,  // GET_PANEL_DATA
  action: 1,  // GET_INITIAL_DATA
  action: 2,  // SAVE_GRAPHIC_DATA
  action: 3,  // UPDATE_ENTRY
  action: 4,  // GET_PANELS_LIST
  action: 5,  // GET_PANEL_RANGE_INFO
  action: 6,  // GET_ENTRIES
  action: 7,  // LOAD_GRAPHIC_ENTRY
  action: 8,  // OPEN_ENTRY_EDIT_WINDOW
  action: 9,  // SAVE_IMAGE
  action: 10, // SAVE_LIBRARY_DATA
  action: 11, // DELETE_IMAGE
  action: 12, // GET_SELECTED_DEVICE_INFO
  action: 13, // BIND_DEVICE
  */

  static DATA_SERVER_ONLINE = -1

  static GET_PANEL_DATA = 0
  static GET_INITIAL_DATA = 1
  static SAVE_GRAPHIC = 2
  static UPDATE_ENTRY = 3
  static GET_PANELS_LIST = 4
  static GET_PANEL_RANGE_INFO = 5
  static GET_ENTRIES = 6
  static LOAD_GRAPHIC_ENTRY = 7
  static OPEN_ENTRY_EDIT_WINDOW = 8
  static SAVE_IMAGE = 9
  static SAVE_LIBRARY_DATA = 10
  static DELETE_IMAGE = 11
  static GET_SELECTED_DEVICE_INFO = 12
  static BIND_DEVICE = 13

  static GET_PANEL_DATA_RES = 'GET_PANEL_DATA_RES'
  static GET_INITIAL_DATA_RES = 'GET_INITIAL_DATA_RES'
  static SAVE_GRAPHIC_RES = 'SAVE_GRAPHIC_RES'
  static UPDATE_ENTRY_RES = 'UPDATE_ENTRY_RES'
  static GET_PANELS_LIST_RES = 'GET_PANELS_LIST_RES'
  static GET_PANEL_RANGE_INFO_RES = 'GET_PANEL_RANGE_INFO_RES'
  static GET_ENTRIES_RES = 'GET_ENTRIES_RES'
  static LOAD_GRAPHIC_ENTRY_RES = 'LOAD_GRAPHIC_ENTRY_RES'
  static OPEN_ENTRY_EDIT_WINDOW_RES = 'OPEN_ENTRY_EDIT_WINDOW_RES'
  static SAVE_IMAGE_RES = 'SAVE_IMAGE_RES'
  static SAVE_LIBRARY_DATA_RES = 'SAVE_LIBRARY_DATA_RES'
  static DELETE_IMAGE_RES = 'DELETE_IMAGE_RES'
  static GET_SELECTED_DEVICE_INFO_DATA = 'GET_SELECTED_DEVICE_INFO_DATA'
  static BIND_DEVICE_RES = 'BIND_DEVICE_RES'
}

export default MessageType
