

class MessageType {

  /*
  action: 0,  // GET_PANEL_DATA / GET_PANEL_DATA_RES ✔
  action: 1,  // GET_INITIAL_DATA / GET_INITIAL_DATA_RES ✔
  action: 2,  // SAVE_GRAPHIC_DATA / SAVE_GRAPHIC_DATA_RES ✔
  action: 3,  // UPDATE_ENTRY / UPDATE_ENTRY_RES ✔
  action: 4,  // GET_PANELS_LIST / GET_PANELS_LIST_RES ✔
  action: 5,  // GET_PANEL_RANGE_INFO / GET_PANEL_RANGE_INFO_RES ❓！
  action: 6,  // GET_ENTRIES / GET_ENTRIES_RES ✔
  action: 7,  // LOAD_GRAPHIC_ENTRY / LOAD_GRAPHIC_ENTRY_RES ✔
  action: 8,  // OPEN_ENTRY_EDIT_WINDOW / OPEN_ENTRY_EDIT_WINDOW_RES ✔
  action: 9,  // SAVE_IMAGE / SAVE_IMAGE_RES ✔
  action: 10, // SAVE_LIBRARY_DATA / SAVE_LIBRARY_DATA_RES | T3 SAVE_LIBRAY_DATA / SAVE_LIBRAY_DATA_RES ✔❓
  action: 11, // DELETE_IMAGE / DELETE_IMAGE_RES
  action: 12, // GET_SELECTED_DEVICE_INFO / GET_SELECTED_DEVICE_INFO_RES ✔
  action: 13, // BIND_DEVICE / BIND_DEVICE_RES ❓！
  */

  // Only used for the websocket server to notify the browser side that the data server (T3 application) is back online
  static DATA_SERVER_ONLINE = -1

  static GET_PANEL_DATA = 0
  static GET_INITIAL_DATA = 1
  static SAVE_GRAPHIC_DATA = 2
  static UPDATE_ENTRY = 3
  static GET_PANELS_LIST = 4
  static GET_PANEL_RANGE_INFO = 5
  static GET_ENTRIES = 6
  static LOAD_GRAPHIC_ENTRY = 7
  static OPEN_ENTRY_EDIT_WINDOW = 8
  static SAVE_IMAGE = 9
  static SAVE_LIBRARY_DATA = 10
  static DELETE_IMAGE = 11
  static GET_SELECTED_DEVICE_INFO = 12
  static BIND_DEVICE = 13

  static GET_PANEL_DATA_RES = 'GET_PANEL_DATA_RES'
  static GET_INITIAL_DATA_RES = 'GET_INITIAL_DATA_RES'
  static SAVE_GRAPHIC_DATA_RES = 'SAVE_GRAPHIC_DATA_RES'
  static UPDATE_ENTRY_RES = 'UPDATE_ENTRY_RES'
  static GET_PANELS_LIST_RES = 'GET_PANELS_LIST_RES'
  static GET_PANEL_RANGE_INFO_RES = 'GET_PANEL_RANGE_INFO_RES'
  static GET_ENTRIES_RES = 'GET_ENTRIES_RES'
  static LOAD_GRAPHIC_ENTRY_RES = 'LOAD_GRAPHIC_ENTRY_RES'

  //❓
  static OPEN_ENTRY_EDIT_WINDOW_RES = 'OPEN_ENTRY_EDIT_WINDOW'
  static SAVE_IMAGE_RES = 'SAVE_IMAGE_RES'

  //❓
  static SAVE_LIBRARY_DATA_RES = 'SAVE_LIBRAY_DATA_RES'
  static DELETE_IMAGE_RES = 'DELETE_IMAGE_RES'
  static GET_SELECTED_DEVICE_INFO_RES = 'GET_SELECTED_DEVICE_INFO_RES'
  static BIND_DEVICE_RES = 'BIND_DEVICE_RES'
}

export default MessageType
